### PR TITLE
Added class member std::vector<KinBodyPtr> objKinBodyPtrs.

### PR DESCRIPTION
**Pull request by serna92**
- Added class member on WorldRPCResponder.h to store kinbodies from generic objects in order to delete them with the `world del all` RPC command.

- WorldRPCResponder modified to be able to add a kinbodies from a xml file with `world mk obj filepath` and del them with `world del all`.

### CODE REVIEW

**Comment by jgvictores** [comment]
Code looks good. Could you rename the PR from "global variable" to "class member"?

**Comment by PeterBowman** [comment]
Cross-referencing issue and PR: #33.

**Review by PeterBowman — COMMENTED** [review]
Tested and working :+1:. For the sake of completion, I'd update the [help command](https://github.com/roboticslab-uc3m/asibot-main/blob/5ae7735/src/libraries/RlPlugins/ravebot/WorldRpcResponder.cpp#L16) with the corresponding instructions, but it's not crucial.

**Comment by jgvictores** [comment]
Updated help at 2dea007f1b492bebd19df65f3a493cf424f8eb26

**Pull request merged**
